### Your code here

# install.packages("XML")
# install.packages("RCurl")

library("XML")
library("RCurl")

### Q2. Download html file from the url below and call it html_text. (2 pts)
### Open the website and ***get an overview of it before coding***.
### We will be working on the data from one of the tables in
### list of countries by electricity production from renewable sources data

url = "https://en.wikipedia.org/wiki/List_of_countries_by_electricity_production_from_renewable_sources"

### Your code here:

html_text <- getURL(url)

### Q3. Read the tables from html_text, set the 1st row as header.
### Now you should have a list object in R containing one data frame, with the renewable resource data.
### Extract the data frame and name it "renew". (2 pts)

### Your code here:

renewablelist <- readHTMLTable(html_text, header = TRUE)
renew <- renewablelist[[1]]
class(renew)

### Q4. Let's simplify the data frame.
### Remove all other columns except country name, and the major renewable sources.
### These are Hydropower, Wind power, Biomass and waste, Solar power.
### Rename the 5 columns "Country", "Hydro", "Wind", "Bio", "Solar". (2 pts)

### Your code here:
renew <- renew[,c(1,6:9)]
names(renew) <- c("Country", "Hydro", "Wind", "Bio", "Solar")

### Q5. Replace the missing values with the median for the variable. 
### (This is a crude but efficient way of treating missing values.) (6 pts)
### (Note: there are commas in relatively large numbers; think about how to convert 
### factor type values to numeric values, especially the example from class.) 

###Your Code:
#renew_check <- renew  # for comparing to original

clean_power_data <- function(energy){
  # funcname: clean_power_data
  # inputs  : A factor of energy values
  # outputs : A vector of energy values with commas removed and NA set to the median value for the vector
  # purpose : Cleaning data for Q5
  # related : NA
  # auth/dt : ID35, 2019-04-08
  
  energy <- as.numeric(gsub(",","",as.character(energy))) # de-factor with as.character, remove comma and make numeric
  energy[is.na(energy)] <- median(energy, na.rm = TRUE)
  return(energy)
  
}

for(i in 2:5){
  renew[,i] <- clean_power_data(renew[,i])
}


### Q6. Create a new column called "Power_from_renew" in the renew data frame,
### that is the sum of all the power generated by the major renewal energy source.(2 pts)

### Your code here

renew$Power_from_renew <- rowSums(renew[,2:5])